In [1]:
from src.loader.reader import Reader, Dataset_BigEarthNet

In [2]:
reader = Reader("~/storage_ds/BigEarthNet-S2",'/root/storage_ds/metadata.parquet')

2025-08-13 12:32:17.285 | INFO     | src.loader.reader:__init__:208 - Initializing the Reader, structuring the paths and files.
2025-08-13 12:32:17.724 | INFO     | src.loader.reader:parent_folders:260 - Found 115 folders in /root/storage_ds/BigEarthNet-S2
2025-08-13 12:32:23.540 | INFO     | src.loader.reader:_create_lookup_structures:244 - Created lookup structures for 480038 patches
2025-08-13 12:32:23.542 | INFO     | src.loader.reader:__init__:228 - None


Number of parent folders: 115
Number of total patches found it: 549488


In [3]:
label_to_idx = {'Agro-forestry areas': 0,
                'Arable land': 1,
                'Beaches, dunes, sands': 2,
                'Broad-leaved forest': 3,
                'Coastal wetlands': 4,
                'Complex cultivation patterns': 5,
                'Coniferous forest': 6,
                'Industrial or commercial units': 7,
                'Inland waters': 8,
                'Inland wetlands': 9,
                'Land principally occupied by agriculture, with significant areas of natural vegetation': 10,
                'Marine waters': 11,
                'Mixed forest': 12,
                'Moors, heathland and sclerophyllous vegetation': 13,
                'Natural grassland and sparsely vegetated areas': 14,
                'Pastures': 15,
                'Permanent crops': 16,
                'Transitional woodland, shrub': 17,
                'Urban fabric': 18}

In [4]:
dataset = Dataset_BigEarthNet(reader=reader,
                              strip_bands=["B02", "B03", "B04"],
                              img_size=120,
                              upsample_mode='bicubic',
                              normalize=False,
                              small_fraction=0.2,
                              split_train_test='validation',
                              dict_one_hot=label_to_idx)

2025-08-13 12:32:42.113 | INFO     | src.loader.reader:__init__:451 - validation split, with length of 122342
2025-08-13 12:32:42.115 | WARNING  | src.loader.reader:__init__:459 - Small sample selected. Dataset is reduced!
2025-08-13 12:32:42.116 | INFO     | src.loader.reader:__init__:460 - validation split, with length of 24468
2025-08-13 12:32:42.117 | INFO     | src.loader.reader:__init__:469 - Bands orded by: ['B02', 'B03', 'B04']


In [6]:
array =dataset.calculate_unbalanced_df()

2025-08-13 12:35:27.761 | INFO     | src.loader.reader:calculate_unbalanced_df:513 - Unbalanced results: {'Agro-forestry areas': 3279, 'Arable land': 11276, 'Beaches, dunes, sands': 162, 'Broad-leaved forest': 5027, 'Coastal wetlands': 247, 'Complex cultivation patterns': 3429, 'Coniferous forest': 7195, 'Industrial or commercial units': 694, 'Inland waters': 3256, 'Inland wetlands': 1190, 'Land principally occupied by agriculture, with significant areas of natural vegetation': 4577, 'Marine waters': 2552, 'Mixed forest': 7443, 'Moors, heathland and sclerophyllous vegetation': 1127, 'Natural grassland and sparsely vegetated areas': 231, 'Pastures': 5464, 'Permanent crops': 2821, 'Transitional woodland, shrub': 7086, 'Urban fabric': 3310}


In [18]:
import torch
import numpy as np
tt = torch.tensor(array)

In [21]:
tt.reshape(19,1,1)

tensor([[[ 3279]],

        [[11276]],

        [[  162]],

        [[ 5027]],

        [[  247]],

        [[ 3429]],

        [[ 7195]],

        [[  694]],

        [[ 3256]],

        [[ 1190]],

        [[ 4577]],

        [[ 2552]],

        [[ 7443]],

        [[ 1127]],

        [[  231]],

        [[ 5464]],

        [[ 2821]],

        [[ 7086]],

        [[ 3310]]])

In [23]:
torch.tensor(array[:,np.newaxis, np.newaxis]).shape

torch.Size([19, 1, 1])

In [9]:
tt.shape

torch.Size([19])

In [32]:
dataset.__getitem__(0)[0][0,:]

tensor([[965., 996., 983.,  ..., 255., 197., 218.],
        [926., 959., 995.,  ..., 213., 220., 218.],
        [861., 880., 949.,  ..., 267., 244., 230.],
        ...,
        [259., 256., 257.,  ..., 661., 683., 702.],
        [252., 246., 249.,  ..., 656., 691., 704.],
        [256., 248., 243.,  ..., 654., 702., 727.]])

In [35]:
dataset.__getitem__(0)[0][0,:]

tensor([[595., 625., 628.,  ..., 248., 172., 182.],
        [567., 621., 626.,  ..., 149., 163., 203.],
        [558., 561., 582.,  ..., 224., 200., 203.],
        ...,
        [180., 196., 212.,  ..., 776., 833., 820.],
        [182., 195., 191.,  ..., 781., 800., 819.],
        [175., 182., 183.,  ..., 761., 829., 863.]])

In [ ]:
dataset.reader.me

In [41]:
dataset.reader.metadata_parquet.loc[dataset.reader.metadata_parquet['patch_id'].isin(dataset.patch_ids_array)]

,patch_id,labels,split,country,s1_name,s2v1_name,contains_seasonal_snow,contains_cloud_or_shadow
83,S2A_MSIL2A_20170613T101031_N9999_R022_T33UUP_3...,"[Arable land, Broad-leaved forest, Inland wate...",validation,Austria,S1B_IW_GRDH_1SDV_20170612T165809_33UUP_33_69,S2A_MSIL2A_20170613T101031_33_69,False,False
84,S2A_MSIL2A_20170613T101031_N9999_R022_T33UUP_3...,"[Arable land, Broad-leaved forest, Inland wate...",validation,Austria,S1B_IW_GRDH_1SDV_20170612T165809_33UUP_33_70,S2A_MSIL2A_20170613T101031_33_70,False,False
105,S2A_MSIL2A_20170613T101031_N9999_R022_T33UUP_3...,"[Broad-leaved forest, Complex cultivation patt...",validation,Austria,S1B_IW_GRDH_1SDV_20170612T165809_33UUP_34_69,S2A_MSIL2A_20170613T101031_34_69,False,False
106,S2A_MSIL2A_20170613T101031_N9999_R022_T33UUP_3...,"[Broad-leaved forest, Complex cultivation patt...",validation,Austria,S1B_IW_GRDH_1SDV_20170612T165809_33UUP_34_70,S2A_MSIL2A_20170613T101031_34_70,False,False
107,S2A_MSIL2A_20170613T101031_N9999_R022_T33UUP_3...,"[Broad-leaved forest, Complex cultivation patt...",validation,Austria,S1B_IW_GRDH_1SDV_20170612T165809_33UUP_34_71,S2A_MSIL2A_20170613T101031_34_71,False,False
...,...,...,...,...,...,...,...,...
96384,S2A_MSIL2A_20171101T094131_N9999_R036_T35VNJ_6...,"[Coniferous forest, Inland waters]",validation,Finland,S1B_IW_GRDH_1SDV_20171101T153951_35VNJ_60_74,S2A_MSIL2A_20171101T94132_60_74,False,False
96385,S2A_MSIL2A_20171101T094131_N9999_R036_T35VNJ_6...,"[Coniferous forest, Inland waters]",validation,Finland,S1B_IW_GRDH_1SDV_20171101T153951_35VNJ_60_76,S2A_MSIL2A_20171101T94132_60_76,False,False
96398,S2A_MSIL2A_20171101T094131_N9999_R036_T35VNJ_6...,"[Broad-leaved forest, Coniferous forest, Inlan...",validation,Finland,S1B_IW_GRDH_1SDV_20171101T042417_35VNJ_61_13,S2A_MSIL2A_20171101T94132_61_13,False,False
96399,S2A_MSIL2A_20171101T094131_N9999_R036_T35VNJ_6...,"[Broad-leaved forest, Coniferous forest, Inlan...",validation,Finland,S1B_IW_GRDH_1SDV_20171101T042417_35VNJ_61_14,S2A_MSIL2A_20171101T094131_61_14,False,False


In [31]:
reader.__getitem__('S2A_MSIL2A_20170613T101031_N9999_R022_T33UUP_33_69')[0]['B04']

array([[965, 996, 983, ..., 255, 197, 218],
       [926, 959, 995, ..., 213, 220, 218],
       [861, 880, 949, ..., 267, 244, 230],
       ...,
       [259, 256, 257, ..., 661, 683, 702],
       [252, 246, 249, ..., 656, 691, 704],
       [256, 248, 243, ..., 654, 702, 727]], dtype=uint16)